### PR TITLE
feat(csp): add nonce to GTM script tag

### PR DESCRIPTION
**Pull request by liollury**
Hello,

I need to add CSP nonce to GTM script tag, please take a look to this PR.

Thank you.

### CODE REVIEW

**Comment by liollury** [comment]
@mzuccaroli is it possible to publish a minor version with this patch (if patch is ok for you) ? I need it for my project.
Thank you.

**Comment by mzuccaroli** [comment]
I'm working on in, I think I will publish by the weekend, thank you for the contribution ;)

**Comment by mzuccaroli** [comment]
I succesfully merged your PR, and released the 1.4.2 version, i also added you in the contributors list.
Thsank you so much for your contribution!

**Comment by liollury** [comment]
amazing, thanks a lot !

**Pull request merged**
