### PR TITLE
Large dependency upgrade

### PR DESCRIPTION
**Pull request by bursauxa**
- Updated all dependencies to latest version, or close to latest
- Replaced tilde versioning with hat versioning (https://github.com/mzuccaroli/angular-google-tag-manager/issues/108)
- Exceptions to the above: `zone.js` still in version 0.x and `typescript` is a special case for the Angular compiler
- Removed `tslint`, as it no longer has any effect: executing `npm run lint` would state there was no linter installed
- Removed `tsickle` and the closure compiler option, as they do not support any Typescript above 4.3
- Updated `build:prod` script for Angular 13 standards

### CODE REVIEW

**Comment by mzuccaroli** [comment]
thank you @bursauxa 
will test & merge ASAP

**Review by shyallegro — APPROVED** [review]
looks great, also would love to see this get committed

**Comment by kanidjar** [comment]
hi @mzuccaroli, any chance to get this merged soon?

**Comment by mzuccaroli** [comment]
sorry for the delay, it's a tough period, i'll try to release it within this week

**Comment by mzuccaroli** [comment]
@bursauxa  
im' testing your PR, there are some problems with the "ng build --configuration prod" script, have you tested it with a clean installation?  (the old "ng build --prod" is still working )

there is also a minor issuo with projects/angular-google-tag-manager/package.json that is not aligned with the external packcage.json but I fixed that

**Comment by mzuccaroli** [comment]
I pushed the fixed PR on develop @bursauxa  can you double-check it for me?

**Comment by bursauxa** [comment]
Hello @mzuccaroli
What you are saying about the `prod` script is surprising, because it comes from Angular cli itself. If you run a build, you should get a warning that `--prod` is deprecated, and the change I made is the one suggested by the cli. I changed it on many of our projects without issue, and the deprecation warning disappeared.

However I guess you could have an issue with it not working if you have a global install of `angular-cli` that is on an older version. Would that be your case?

**Comment by mzuccaroli** [comment]
found the problem, I was calling the script via `npm run`and not via `npx` 
with  the syntax `--configuration=production`  works both ways

**Comment by bursauxa** [comment]
That problem makes sense if you are in the situation I mentioned above (an outdated global install of `angular-cli`), as `npx` will ignore the global install and thus use the version specified in `package.json` ;)

The other changes you fixed in the `package.json` files are completely fine, so I guess we can merge now 👏

**Comment by mzuccaroli** [comment]
I'ts strange because the output of `npm run ng version` and `npx ng version` are the same (Angular CLI: 13.1.2) , however `--configuration=production` works fine and I'm proceeding with the release

**Comment by mzuccaroli** [comment]
@shyallegro  @kanidjar  V 1.5.0 is released, thank @bursauxa  for your contribution and your support

**Comment by bursauxa** [comment]
You are welcome, thank you for having this library in the first place!

**Comment by kanidjar** [comment]
thank you @mzuccaroli

**Pull request closed without merging**
