### PR TITLE
Module for root support

### PR DESCRIPTION
**Pull request by GravlLift**
This PR adds the ability to import this package via a call to GoogleTagManagerModule.forRoot in an application's root module imports. This permits a single import point with strongly-typed options, as demonstrated in the updated README, removing the need for multiple provider entries powered by strings.

All prior functionality has been preserved for backward compatibility.

Continuation of https://github.com/mzuccaroli/angular-google-tag-manager/pull/27

### CODE REVIEW

**Comment by GravlLift** [comment]
Responding to https://github.com/mzuccaroli/angular-google-tag-manager/pull/27#issuecomment-695799262
> hi @GravlLift , sorryfor my absence, I have released the angular 10 version of the library and the migration was a bit challenging, i took a quick look to your PR, can you update your branch and the pr to the new version of the lib and remove the vscode folder from the commit? (should be gitignored)

I went and rebased off the latest master and resolved merge conflicts.

Regarding the .gitignore and .vscode, it looks like the inclusion of tasks.json and settings.json the gitignore configuration that allowed them to exist appears to be defined in your master branch: 

https://github.com/mzuccaroli/angular-google-tag-manager/blob/master/.gitignore#L27-L33
```
# IDE - VSCode
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
.history/*
```

I have removed them from this PR. However, having shared .vscode files can be useful, you may want to consider leaving that gitignore as is and allowing for shared VS Code tasks.

**Comment by mzuccaroli** [comment]
I have some problem on building your branch:
`------------------------------------------------------------------------------
Building entry point 'angular-google-tag-manager'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: projects/angular-google-tag-manager/src/lib/angular-google-tag-manager.module.ts:6:58 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

6   public static forRoot(config: GoogleTagManagerConfig): ModuleWithProviders {
                                                           ~~~~~~~~~~~~~~~~~~~
`

**Comment by GravlLift** [comment]
Yup, @mzuccaroli, looks like you've updated to Angular 10 since I opened this PR. I have updated the code to conform to the Angular 10 API.

**Comment by mzuccaroli** [comment]
Yes, I warn you in the [previous PR](https://github.com/mzuccaroli/angular-google-tag-manager/pull/27#issuecomment-695799262), I'm currently testing your branch an will merge it soon

**Comment by mzuccaroli** [comment]
@GravlLift  succesfully merged, I updated the internali library readme, version an add you to the contributor list
Good Job!

**Pull request merged**
