### PR TITLE
Added eviroment support

### PR DESCRIPTION
**Pull request by nilsthomann**

### CODE REVIEW

**Comment by mzuccaroli** [comment]
thanks for the contribution, i'll check it as soon as possible

**Comment by mzuccaroli** [comment]
I'm working on the merge on develop branch and testing all the things, is that ok if include you in the package contributors?

**Comment by nilsthomann** [comment]
> I'm working on the merge on develop branch and testing all the things, is that ok if include you in the package contributors?

The Pull Request was kind of crapy. That's the reason why I closed it. If you have the time to improve the PR, a mention in the package contributors would be nice. I've you don't have the time I could open a new PR with refactored code.

**Comment by mzuccaroli** [comment]
I started working on it but I dont have so much time, if you want to create a better PR on develop be my guess ;)
I'm looking for unexpected behaviors when no enviromnents are passed in the @inject @Inject('googleTagManagerEviromentId') 
have you tried with the [@optional](https://angular.io/api/core/Optional) decorator?

**Pull request closed without merging**
