### PR TITLE
REFACTORED: Added eviroment support

### PR DESCRIPTION
**Pull request by nilsthomann**

### CODE REVIEW

**Comment by mzuccaroli** [comment]
I have merged the code in develop branch and updated readme changelog ecc..
could you test it a little bit before we publish the new version?

**Comment by nilsthomann** [comment]
I've tested it in a productive application and it worked perfect. Maybe you could add these two lines as optional values in the README.md
```
  { provide: 'googleTagManagerAuth', useValue: YOUR_GTM_AUTH},
  { provide: 'googleTagManagerPreview', useValue: YOUR_GTM_PREVIEW},
```

**Comment by mzuccaroli** [comment]
I have already addet them in the new  "Custom configuration and GTM environments" section of the readme
this afternool I will release the new npm package ;)

**Comment by nilsthomann** [comment]
@mzuccaroli you've released the project folder and not the dist folder. Is it possible to publish a new version with the compiled code? And I recognized your contributors link in the README.md is of another repo.

**Comment by mzuccaroli** [comment]
the dist folder should be git-ignored, you can generate it by running "npm run build" or retrieve the final package directly from npm https://www.npmjs.com/package/angular-google-tag-manager

I fixed the typo on the contributors and updated the version

**Comment by nilsthomann** [comment]
No, you got me wrong. The released version on NPM is not the compiled code it's the uncompiled project folder.

**Comment by mzuccaroli** [comment]
my fault, fixed

**Pull request merged**
